version: '3.8'

services:
  files-backup:
    build:
      context: .
    image: ghcr.io/concepting-com-br/files-backup:${BUILD_VERSION}
    container_name: files-backup
    hostname: files-backup
    depends_on:
      - sftp
      - etcd

  sftp:
    image: ghcr.io/concepting-com-br/sftp:1.1.0
    container_name: sftp
    hostname: sftp
    depends_on:
      - etcd

  etcd:
    image: ghcr.io/concepting-com-br/etcd:1.1.0
    container_name: etcd
    hostname: etcd
    ports: 
      - "2379:2379"
    volumes:
      - ./etc/settings.json:/home/user/etc/files-backup.json
      - ../sftp/etc/settings.json:/home/user/etc/sftp.json
      - etcd-data:/home/user/data

volumes:
  etcd-data:
  